version: '2'
services:
    db:
        restart: always
    static:
        build: ./nginx
        volumes:
            - data:/usr/share/nginx/data
        links:
            - web:gunicorn
        ports: 
            - "80:80"
        restart: always
    web:
        command: gunicorn --workers=4 --bind=0.0.0.0:8000 xxicatalog.wsgi 
        restart: always
