version: '2'
services:
    db:
        build: 
            context: .
            dockerfile: postgres_ru_Dockerfile
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
            PGDATA: "/var/lib/postgresql/data/pgdata"
    static:
        build: ./nginx
        ports: 
            - "8080:80"
        volumes:
            - data:/usr/share/nginx/data
        links:
            - web:gunicorn
    web:
        build: .
        command: gunicorn --workers=4 --bind=0.0.0.0:8000 xxicatalog.wsgi 
        depends_on:
            - db
        volumes:
            - data:/data
        environment:
            PSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
            DJANGO_SECRET_KEY:
volumes:
    data:
        external:
            name: xxicatalog
