# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=512, verbose_name='Подзаголовок')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор по каталогу')),
                ('city', models.CharField(blank=True, max_length=15, verbose_name='Город')),
                ('publisher', models.CharField(blank=True, max_length=128, verbose_name='Издательство')),
                ('page_amount', models.CharField(blank=True, max_length=15, verbose_name='Количество страниц')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('article', models.CharField(blank=True, max_length=5, verbose_name='Артикул')),
                ('annotation', models.TextField(blank=True, verbose_name='Аннотация по каталогу (из базы)')),
                ('book_description', models.TextField(blank=True, verbose_name='Аннотация по сайту')),
                ('book_cover', models.ImageField(blank=True, upload_to='book_covers', verbose_name='Фото обложки')),
                ('book_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор книги на сайте')),
            ],
            options={
                'verbose_name_plural': 'Издания',
                'verbose_name': 'Издание',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Рубрики',
                'verbose_name': 'Рубрика',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рубрики на сайте')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес рубрики на сайте')),
                ('books', models.ManyToManyField(related_name='folders', to='main.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.Category', verbose_name='Рубрика'),
        ),
    ]
