# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=512, verbose_name='Подзаголовок')),
                ('author', models.CharField(max_length=255, verbose_name='Автор по каталогу')),
                ('publisher', models.CharField(max_length=128, verbose_name='Город и издательство')),
                ('page_amount', models.CharField(max_length=15, verbose_name='Количество страниц')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('article', models.CharField(max_length=5, verbose_name='Артикул')),
                ('annotation', models.TextField(verbose_name='Аннотация по каталогу (из базы)')),
                ('book_description', models.TextField(verbose_name='Аннотация по сайту')),
                ('book_cover', models.ImageField(upload_to='', verbose_name='Фото обложки')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.Category', verbose_name='Рубрика'),
        ),
    ]
