# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_amount',
            field=models.CharField(blank=True, max_length=50, verbose_name='Количество страниц'),
        ),
    ]
