# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация по каталогу (из базы)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='article',
            field=models.CharField(blank=True, max_length=5, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор по каталогу'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, verbose_name='Аннотация по сайту'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_amount',
            field=models.CharField(blank=True, max_length=15, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, verbose_name='Город и издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=512, verbose_name='Подзаголовок'),
        ),
    ]
