# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 08:18
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160907_0852'),
    ]

    operations = [
        TrigramExtension(),
    ]
