# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160826_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order_field',
        ),
    ]
