# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160903_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title', 'subtitle', 'author'), 'verbose_name': 'Издание', 'verbose_name_plural': 'Издания'},
        ),
    ]
