# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рубрики на сайте')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес рубрики на сайте')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.CharField(blank=True, max_length=15, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='book_covers', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='folder',
            name='books',
            field=models.ManyToManyField(related_name='folders', to='main.Book'),
        ),
    ]
