# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160912_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_contents',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
