# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160826_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор книги на сайте'),
        ),
    ]
